language: node_js
node_js:
- '0.12'
- '4'
- '5'
sudo: false
script: make test
env:
  global:
    - secure: BXSIkMLUxKrvUBOoJH+HUv9fMrVkFOnkTu1Tu4lnkDeOGAom2jTxobZ+ViDC4vzORpvksnFEqOF0tCGTU6juYVBE9nCeLa2yV9GJfeV5Oz18kRk1wKvhy6R9V2iQfN+VL5R/raYrLIhwnyhPwQoBnUL2iEVbFQTJaON0v2Qhhpiwxktr2X/SWsJgT+JwSreB4Mn48XPV9EtDsuCFEtfjPAEZFuDxnAnA2QExHK3rM8PMfpO70iJzYl1zM/tg2DOPR78QcAzUj8vm1LDrhoMGbYu7eG5AewY3J9Qzc0jamHUFzHTh5DeoyYHEohH/K9TNGcaVDrm4oLjODU8MGwWuPDbP7YJKRXEFFrj4v4xH3ORpgnBFVyUuCL8sX7LWGr1lCFVi5vpzANX6I1t07mDja1VK/wBk23NdXglQBKRVqvuaA5DMuMSZQf87Kgi0dEqbHJgs2IidKutZEkzR+1EgCoHUQFDkuDdNWZ0DkNFeZHBv+p3+iJ+f6MZgpBoXqvgkUTNGK+6U4rvQZAD8fRbixasXD44jNhh70zL+SRsBrcA+I3NX9tu8qe7wEYFlAC4PNGRpiTnaY94h/JztKvKxAZW1ED876hRd9nPtiG1mSeoeTceAQrbt/UGCb/f2yg65IYvhsy3QXLnB8+tID9EzVnfDfj/fuxWhUCMuYW+tBrw=
    - secure: b5gdcbwHzdKCRmSut5cZ5GVMbDNOaGtiL5M5ujcFz5Kth5fhSripweaK/9Cm9Ku2VIxaryhQEvwptAonLLQahjK47Kfw6U99q4CGGV9Kq8SniFxgp43rr5X3NHf7lKdH2auO8fmiVK2aB1jYhvxrpN3kN5vbicRMt+RPXsMOgdmuRBYmehvZzp023YLizVU9TRzibzzDgjuU5hK1+gelA2CdUJ6kTmFMWdJKX7Izc3UW/QItMDtVaou5MaFT8PJMXrUzdjWXB3c6kZlZnksyPugATQ+/f5x+TIyCSfazzF83Y//kULJkRYvDTQXwziD00MCdwePVzP+bTh7ziwQtF8oA58AnGEGAH5YenNdTM16HQA0BAGw0J71gnWW/zCVa8rZcBNmHbPLAff7K29OpGNQOX/UFideM08vo0rJWCjDpyjSLVYZW/4dMhRdxSr1jFF+strxz7VXi9aCDuOd5MVsTOM4MhkVt4e5jnhbsPBF9dWnnnmU1Z0BwF/O87ga6D9aa62SNv049NO9lRHcdSU1Ve40mdzyNPrvu9UT5RtfZ77LTfo4IT1RSGjRVUn22TejKPFEtIwryGymHqjaN5wVe780sVH0FuozhoVZSdw1WwpjZpbz54ephpcmDu+7F4Ty6j1GJXA4tK92SmfLMfS/RUJQX8f+SPzemuL8IvkQ=
    - AWS_REGION=us-west-2
